// Code generated by protoc-gen-go.
// source: count.proto
// DO NOT EDIT!

/*
Package count is a generated protocol buffer package.

It is generated from these files:
	count.proto

It has these top-level messages:
	CountRequest
	CountReply
	HelloRequest
	HelloReply
	GoodbyeRequest
	GoodbyeReply
*/
package count

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CountRequest struct {
	Count int32 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *CountRequest) Reset()                    { *m = CountRequest{} }
func (m *CountRequest) String() string            { return proto.CompactTextString(m) }
func (*CountRequest) ProtoMessage()               {}
func (*CountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CountRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type CountReply struct {
	Count int32 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *CountReply) Reset()                    { *m = CountReply{} }
func (m *CountReply) String() string            { return proto.CompactTextString(m) }
func (*CountReply) ProtoMessage()               {}
func (*CountReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CountReply) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type HelloRequest struct {
	Start int32 `protobuf:"varint,1,opt,name=start" json:"start,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HelloRequest) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

type HelloReply struct {
	Ack bool `protobuf:"varint,1,opt,name=ack" json:"ack,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HelloReply) GetAck() bool {
	if m != nil {
		return m.Ack
	}
	return false
}

type GoodbyeRequest struct {
	Goodbye bool `protobuf:"varint,1,opt,name=goodbye" json:"goodbye,omitempty"`
}

func (m *GoodbyeRequest) Reset()                    { *m = GoodbyeRequest{} }
func (m *GoodbyeRequest) String() string            { return proto.CompactTextString(m) }
func (*GoodbyeRequest) ProtoMessage()               {}
func (*GoodbyeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GoodbyeRequest) GetGoodbye() bool {
	if m != nil {
		return m.Goodbye
	}
	return false
}

type GoodbyeReply struct {
	FinalCount int32 `protobuf:"varint,1,opt,name=finalCount" json:"finalCount,omitempty"`
}

func (m *GoodbyeReply) Reset()                    { *m = GoodbyeReply{} }
func (m *GoodbyeReply) String() string            { return proto.CompactTextString(m) }
func (*GoodbyeReply) ProtoMessage()               {}
func (*GoodbyeReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GoodbyeReply) GetFinalCount() int32 {
	if m != nil {
		return m.FinalCount
	}
	return 0
}

func init() {
	proto.RegisterType((*CountRequest)(nil), "CountRequest")
	proto.RegisterType((*CountReply)(nil), "CountReply")
	proto.RegisterType((*HelloRequest)(nil), "HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "HelloReply")
	proto.RegisterType((*GoodbyeRequest)(nil), "GoodbyeRequest")
	proto.RegisterType((*GoodbyeReply)(nil), "GoodbyeReply")
}

func init() { proto.RegisterFile("count.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xce, 0x2f, 0xcd,
	0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe1, 0xe2, 0x71, 0x06, 0x71, 0x83, 0x52,
	0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x44, 0xb8, 0x58, 0xc1, 0xd2, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0xac, 0x41, 0x10, 0x8e, 0x92, 0x12, 0x17, 0x17, 0x54, 0x55, 0x41, 0x4e, 0x25, 0x0e, 0x35, 0x2a,
	0x5c, 0x3c, 0x1e, 0xa9, 0x39, 0x39, 0xf9, 0x48, 0x26, 0x15, 0x97, 0x24, 0x16, 0xc1, 0x55, 0x81,
	0x39, 0x4a, 0x72, 0x5c, 0x5c, 0x50, 0x55, 0x20, 0x93, 0x04, 0xb8, 0x98, 0x13, 0x93, 0xb3, 0xc1,
	0x2a, 0x38, 0x82, 0x40, 0x4c, 0x25, 0x2d, 0x2e, 0x3e, 0xf7, 0xfc, 0xfc, 0x94, 0xa4, 0xca, 0x54,
	0x98, 0x39, 0x12, 0x5c, 0xec, 0xe9, 0x10, 0x11, 0xa8, 0x3a, 0x18, 0x57, 0x49, 0x8f, 0x8b, 0x07,
	0xae, 0x16, 0x64, 0x9a, 0x1c, 0x17, 0x57, 0x5a, 0x66, 0x5e, 0x62, 0x8e, 0x33, 0x92, 0xe3, 0x90,
	0x44, 0x92, 0xd8, 0xc0, 0x5e, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x75, 0x6b, 0x43,
	0x01, 0x01, 0x00, 0x00,
}
